routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin' )->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function (){
    Route::resource('/users', 'UsersController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'surname', 'sa_id_number', 'mobile_number', 'date_of_birth', 'language', 'interests'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'date_of_birth' => 'date',
        'interests' => 'array',
    ];

    public $interest_array = ['Interest 1', 'Interest 2'];


    public $language_array = ['Zulu','Xhosa','Afrikaans','English','Sepedi','Tswana','Sotho','Tsonga','Swati','Venda','Ndebele','SA Sign Language'];

    public function roles(){
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles){
        if($this->roles()->whereIn('name', $roles)->first()){
            return true;
        }
        return false;
    }

    public function hasRole($role){
        if($this->roles()->where('name', $role)->first()){
            return true;
        }
        return false;
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Jobs\SendEmail;
use App\Mail\UserConfirmation;
use App\Role;
use App\User;
use Gate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;
use Illuminate\Auth\Notifications\VerifyEmail;
use Carbon\Carbon;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param array $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],

            'surname' => ['string', 'max:255'],
            'sa_id_number' => ['digits:13'],
            'mobile_number' => ['digits:10'],
            'date_of_birth' => ['date'],
            'language' => ['string'],
            'interests' => ['array'],
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        return view('admin.users.create')->with([ 'interest_array' => $user->interest_array  ]);
    }

    private function getDOBfromID($said){
        //get the DOB from the IDnumber
        $date_of_birth_YY = substr($said, 0, 2);
        $date_of_birth_MM = substr($said, 2, 2);
        $date_of_birth_DD = substr($said, 4, 2);

        $now = date('Y'); //2019
        $nowmil = substr($now, 0, 2);
        $millenium = 19;
        if ($date_of_birth_YY < $nowmil) {
            $millenium = 20;
        }
        return $millenium . $date_of_birth_YY . '-' . $date_of_birth_MM . '-' . $date_of_birth_DD;
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dob = $request['date_of_birth'];

        if (!empty($request['sa_id_number']) && empty($dob) ){
            $dob = $this->getDOBfromID($request['sa_id_number']);
        }

        $user = User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),

            'surname' => $request['surname'],
            'sa_id_number' => $request['sa_id_number'],
            'mobile_number' => $request['mobile_number'],
            'date_of_birth' => $dob,
            'language' => $request['language'],
            'interests' => $request['interests']
        ]);

       // Mail::to($user)->send(new UserConfirmation($user));

        $details = ['email' => $request['email'] ];
        SendEmail::dispatch($details);

        return redirect(route('admin.users.index'))->with('success', 'User added!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //dd($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if (Gate::denies('edit-users')) {
            return redirect(route('admin.users.index'));
        }
        $roles = Role::all();
        return view('admin.users.edit')->with([
                'user' => $user,
                'roles' => $roles
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //dd($request);
        $user->roles()->sync($request->roles);

        $dob = $request['date_of_birth'];

        if (!empty($request['sa_id_number']) && empty($dob) ){
            $dob = $this->getDOBfromID($request['sa_id_number']);
        }

        $user->name = $request['name'];
        $user->email = $request['email'];

        $user->surname = $request['surname'];
        $user->sa_id_number = $request['sa_id_number'];
        $user->mobile_number = $request['mobile_number'];
        $user->date_of_birth = $dob;
        $user->language = $request['language'];
        $user->interests = $request['interests'];

        if(!empty($request['password'])){
            $user->password = Hash::make($request['password']);
        }

        if($user->save()){
            $request->session()->flash('success', $user->name.' has been updated successfully.');
        } else {
            $request->session()->flash('error', 'There was an error updating '.$user->name);
        }

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
        //dd($user);
        if (Gate::denies('delete-users')) {
            return redirect(route('admin.users.index'));
        }
        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create') }}</div>

                <div class="card-body">
                    <form action="{{ route('admin.users.store') }}" method="post" >
                        @csrf

                        <input type="hidden" name="roles[]" value="2">

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="given-name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="surname" class="col-md-4 col-form-label text-md-right">{{ __('Surname') }}</label>

                            <div class="col-md-6">
                                <input id="surname" type="text" class="form-control @error('surname') is-invalid @enderror" name="surname" value="{{ old('surname') }}" required autocomplete="family-name" autofocus>

                                @error('surname')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="sa_id_number" class="col-md-4 col-form-label text-md-right">{{ __('ID Number') }}</label>

                            <div class="col-md-6">
                                <input id="sa_id_number" type="number" maxlength="13" class="form-control  @error('sa_id_number')  is-invalid @enderror" name="sa_id_number" value="{{ old('sa_id_number') }}" autocomplete="sa_id_number" autofocus>

                                @error('sa_id_number')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mobile_number" class="col-md-4 col-form-label text-md-right">{{ __('Cell Number') }}</label>

                            <div class="col-md-6">
                                <input id="mobile_number" type="tel" maxlength="10"  class="form-control @error('mobile_number') is-invalid @enderror" name="mobile_number" value="{{ old('mobile_number') }}" required autocomplete="tel" autofocus>

                                @error('mobile_number')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="date_of_birth" class="col-md-4 col-form-label text-md-right">{{ __('Date of Birth') }}</label>

                            <div class="col-md-6">
                                <input id="date_of_birth" type="date" class="form-control @error('date_of_birth') is-invalid @enderror" name="date_of_birth" value="{{ old('date_of_birth') }}"  autocomplete="date_of_birth" autofocus>

                                @error('date_of_birth')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="language" class="col-md-4 col-form-label text-md-right">{{ __('Language') }}</label>


                            <div class="col-md-6">

                                <select id="language"
                                        class="form-control @error('language') is-invalid @enderror" name="language" value="{{ old('language') }}" required autocomplete="language" autofocus>
                                    <option value="1">Zulu<option/>
                                    <option value="2">Xhosa<option/>
                                    <option value="3">Afrikaans<option/>
                                    <option value="4">English<option/>
                                    <option value="5">Sepedi<option/>
                                    <option value="6">Tswana<option/>
                                    <option	value="7">Sotho<option/>
                                    <option value="8">Tsonga<option/>
                                    <option value="9">Swati<option/>
                                    <option value="10">Venda<option/>
                                    <option value="11">Ndebele<option/>
                                    <option value="12">SA Sign Language<option/>
                                </select>

                                @error('language')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="interests" class="col-md-4 col-form-label text-md-right">{{ __('Interests') }}</label>

                            <div class="col-md-6">
                                @foreach($interest_array as $interest)
                                    <div class="form-check">
                                        <label><input type="checkbox" name="interests[]" value="{{ $interest }}"
                                            >
                                            {{ $interest }}</label>
                                    </div>
                                @endforeach

                                @error('interests')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>




                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit User: {{ $user->name }}</div>

                    <div class="card-body">
                        <form action="{{ route('admin.users.update', $user) }}" method="post" >
                            @csrf
                            {{ method_field('PUT') }}




                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autocomplete="given-name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="surname" class="col-md-4 col-form-label text-md-right">{{ __('Surname') }}</label>

                                <div class="col-md-6">
                                    <input id="surname" type="text" class="form-control @error('surname') is-invalid @enderror" name="surname" value="{{ $user->surname }}" required autocomplete="family-name" autofocus>

                                    @error('surname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="sa_id_number" class="col-md-4 col-form-label text-md-right">{{ __('ID Number') }}</label>

                                <div class="col-md-6">
                                    <input id="sa_id_number" type="number" maxlength="13" class="form-control  @error('sa_id_number')  is-invalid @enderror" name="sa_id_number" value="{{ $user->sa_id_number }}" autocomplete="sa_id_number" autofocus>

                                    @error('sa_id_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="mobile_number" class="col-md-4 col-form-label text-md-right">{{ __('Cell Number') }}</label>

                                <div class="col-md-6">
                                    <input id="mobile_number" type="tel" maxlength="10"  class="form-control @error('mobile_number') is-invalid @enderror" name="mobile_number" value="{{ $user->mobile_number }}" autocomplete="tel" autofocus>

                                    @error('mobile_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="date_of_birth" class="col-md-4 col-form-label text-md-right">{{ __('Date of Birth') }}</label>

                                <div class="col-md-6">
                                    <input id="date_of_birth" type="date" class="form-control @error('date_of_birth') is-invalid @enderror" name="date_of_birth" value="{{ date('Y-m-d', strtotime($user->date_of_birth))  }}"  autocomplete="date_of_birth" autofocus>

                                    @error('date_of_birth')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="language" class="col-md-4 col-form-label text-md-right">{{ __('Language') }}</label>


                                <div class="col-md-6">

                                    <select id="language"
                                            class="form-control @error('language') is-invalid @enderror" name="language" >
                                        @foreach($user->language_array as $language)
                                            <option @if( isset($user->language) && $language == $user->language ) selected @endif>{{ $language }}</option>
                                        @endforeach
                                    </select>

                                    @error('language')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="interests" class="col-md-4 col-form-label text-md-right">{{ __('Interests') }}</label>

                                <div class="col-md-6">
                                    @foreach($user->interest_array as $interest)
                                        <div class="form-check">
                                            <label><input type="checkbox" name="interests[]" value="{{ $interest }}"
                                                          @if( isset($user->interests) && in_array($interest, $user->interests) ) checked @endif>
                                                {{ $interest }}</label>
                                        </div>
                                    @endforeach

                                    @error('interests')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Reset password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password"  autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="roles" class="col-md-4 col-form-label text-md-right">{{ __('Roles') }}</label>
                                <div class="col-md-6">
                                    @foreach($roles as $role)
                                        <div class="form-check">
                                            <label><input type="checkbox" name="roles[]" value="{{ $role->id }}"
                                                          @if($user->roles->pluck('id')->contains($role->id)) checked @endif>
                                                {{ $role->name }}</label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>

                            <a href="{{ route('admin.users.index') }}" class="btn  pull-right">Back</a>
                            <button type="submit" class="btn btn-primary float-right">Update</button>

                        </form>




                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8">

                @if(session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif

                @if(session('warning'))
                    <div class="alert alert-warning">
                        {{ session('warning') }}
                    </div>
                @endif

                @if(session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif

            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"> <h2>Users<a href="{{ route('admin.users.create') }}" class="btn btn-primary float-right">Create</a></div>
                    </h2>
                    <div class="card-body">

                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Surname</th>
                                <th scope="col">Email</th>
                                <th scope="col">Roles</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <th scope="row">{{ $user->name }}</th>
                                    <td>{{ $user->surname }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ implode(',', $user->roles()->get()->pluck('name')->toArray()) }}</td>
                                    <td>
                                        @can('edit-users')
                                            <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-primary">Edit</a>
                                        @endcan
                                    </td>
                                    <td>
                                        @can('delete-users')
                                            <form action="{{ route('admin.users.destroy', $user) }}" method="post" class="d-inline">
                                            @csrf
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-warning">Delete</button>
                                            </form>
                                        @endcan
                                        </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <p>You should only be able to see this page if you are an admin</p>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection